### ISSUE TITLE
DataChannel support to WebRTC-iOS

### ISSUE THREAD

**Issue by JinGuoGe** [aolszak/WebRTC-iOS#1]
Hi, aolszak! Thank you for your contribution. 
Now I'm going to implement real time data communication between two apps.
if you add DataChannel function to your WebRTC-iOS, it will be very big help to me.
My email is jinguoge99@outlook.com. 
I will waiting for your answer. 
Thank you.

**Comment by adarshvcdev** [comment]
HI JinGuoGe , Are you able integrate RTCDataChannel sucessfully?

**Comment by ajaysinghthakur** [comment]
unable to implement RTCDataChannel
